### ISSUE TITLE
Running it in other DE like mate-desktop

### ISSUE THREAD

**Issue by tbrogan** [subgraph/fw-daemon#1]
Can you add support for running it on other desktop environments, like mate desktop? 
Thanks.

**Comment by xSmurf** [comment]
We will not be expanding resources on this. But nothing stop someone to write their own client :) I'll leave the ticket open in the off-chance someone's looking for a project...

**Comment by pepa65** [comment]
I just tried doing this, following the install instructions in the README (comments included):
```bash
git clone -b debian https://github.com/subgraph/fw-daemon.git  # install git first: sudo apt install git
cd fw-daemon
gbp buildpackage -us -uc  # install git-buildpackage first!
dpkg -i /tmp/build-area/fw-daemon*.deb
# This will run into missing dependencies (like gnome-shell), usually solved by: apt-get install -f
# Unfortunately, my internet connection appeared to have gotten blocked..? How is that possible??
# Possible some preconfiguration of certain packages related to internet management?
# Anyway, that whole installation doesn't work anymore, so beware!

**Comment by dma** [comment]
This has been implemented, the original issue will be closed. New issues will be created as development continues.
