### ISSUE TITLE
Split proc library on its own 

### ISSUE THREAD

**Issue by xSmurf** [subgraph/fw-daemon#13]
The proc library should be split out of the project for reuse in https://github.com/subgraph/roflcoptor.

Potentially merged back into https://github.com/subgraph/procsnitch ?

**Comment by david415** [comment]
now that we have go-procsnitch --> https://github.com/subgraph/go-procsnitch
we should remove the proc code from this repo. i dislike code duplication.

**Comment by david415** [comment]
https://github.com/subgraph/fw-daemon/pull/20

**Comment by david415** [comment]
fixed here https://github.com/subgraph/fw-daemon/pull/20

close this ticket
