### ISSUE TITLE
Package for Debian

### ISSUE THREAD

**Issue by bnvk** [subgraph/fw-daemon#15]
because, packaging is fun :smile:

**Comment by xSmurf** [comment]
@bnvk https://github.com/subgraph/fw-daemon/tree/debian ?

**Comment by intrigeri** [comment]
With https://github.com/subgraph/fw-daemon/pull/23 applied I can build a package in a clean pbuilder sid chroot from the `debian` branch, so once my PR is accepted I guess this issue can be closed :)

**Comment by xSmurf** [comment]
This has been fixed for ever :)
