### ISSUE TITLE
Consider giving the GNOME Shell extension a better and less generic name

### ISSUE THREAD

**Issue by intrigeri** [subgraph/fw-daemon#24]
Hi!

I'm writing in the context of wanting to have fw-daemon in Debian proper, some day.

I see that in GNOME Tweak Tools, the GNOME Shell extension is called "Firewall extension". I see two problems with that:
- It's too generic: there may be other firewall management daemons in Debian, that may have their own extension. IMO the extension should reflect which exact firewall management daemon it is about.
- The "extension" word feels wrong here: we're in the "Extensions" tab, so it's implicit that it's an extensions;  I guess that's why none of the other extensions I have installed include this word.

Cheers!

**Comment by brl** [comment]
Totally agree. Fixed!
